---@diagnostic disable: undefined-global, lowercase-global

local config = {
    -- channel 1
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 2
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 3
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 4
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 5
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 6
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 7
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 8
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 9
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 10
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 11
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 12
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 13
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 14
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 15
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    },
    -- channel 16
    { -- cc slots
        { active = false, velocity = false, cc_number = 1},
        { active = false, velocity = false, cc_number = 2},
        { active = false, velocity = false, cc_number = 3},
        { active = false, velocity = false, cc_number = 4},
        { active = false, velocity = false, cc_number = 5},
        { active = false, velocity = false, cc_number = 6},
        { active = false, velocity = false, cc_number = 7},
        { active = false, velocity = false, cc_number = 8},
        { active = false, velocity = false, cc_number = 9},
        { active = false, velocity = false, cc_number = 10},
        { active = false, velocity = false, cc_number = 11},
        { active = false, velocity = false, cc_number = 12},
        { active = false, velocity = false, cc_number = 13},
        { active = false, velocity = false, cc_number = 14},
        { active = false, velocity = false, cc_number = 15},
        { active = false, velocity = false, cc_number = 16}
    }
}

return config